name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install flake8
      run: pip install flake8

    #- name: Lint Python code   # Commenetd as not part of the task scope
    #  run: flake8 app/

    - name: Install hadolint
      run: sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64 && sudo chmod +x /bin/hadolint

    - name: Lint Dockerfile
      run: hadolint Dockerfile

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: lint-and-analyze

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.AZURE_APP_NAME }}:latest .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.AZURE_APP_NAME }}:latest

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure WebApp Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        slot-name: 'production'
        images: ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.AZURE_APP_NAME }}:latest